In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
!pip freeze numpy

appnope==0.1.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.9.11
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
importlib-metadata==0.23
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipython-sql==0.3.9
jedi==0.15.1
Jinja2==2.10.3
json5==0.8.5
jsonschema==3.1.1
jupyter-client==5.3.4
jupyter-core==4.6.0
jupyterlab==1.1.4
jupyterlab-server==1.0.6
MarkupSafe==1.1.1
mistune==0.8.4
mkl-fft==1.0.14
mkl-random==1.1.0
mkl-service==2.3.0
more-itertools==7.2.0
nb-conda-kernels==2.2.2
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.17.2
pandas==0.25.2
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
prettytable==0.7.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
ptyprocess==0.6.0
Pygments==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
pytz==2019.3
pyzmq==18.1.0
Send2Trash==1.5.0
six==1.12.0
SQLAlchemy==1.3.10
sqlparse==0.3.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.3
wcwidth==0.1.7
webencodings==0.5.1
zipp==0.6.0


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
from random import random
a = np.random.rand(2, 3, 5)
#4. Print a.
print (a)

[[[0.16445687 0.84667536 0.30726898 0.80098137 0.19631435]
  [0.02365554 0.30499958 0.53091093 0.49148912 0.53372481]
  [0.32137078 0.00594733 0.33486346 0.20980453 0.20907052]]

 [[0.59928867 0.27620136 0.05585533 0.51427482 0.80348773]
  [0.6332484  0.92814138 0.21252654 0.79758725 0.58489046]
  [0.62901411 0.55465762 0.91307846 0.08720965 0.64480321]]]


In [15]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5, 2, 3))
#6. Print b.
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
#7. Do a and b have the same size? How do you prove that in Python code?
if a.size == b.size :
    print ('A and B have the same size')
else :
    print('A and B are not the same size')

A and B have the same size


In [16]:
#8. Are you able to add a and b? Why or why not?
print (a + b)
#No, because they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [31]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose(1, 2, 0)
print (c)
print (c.shape)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


In [74]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = (a+c)
print (d)
#It worked because both arrays had the same size

[[[1.16445687 1.84667536 1.30726898 1.80098137 1.19631435]
  [1.02365554 1.30499958 1.53091093 1.49148912 1.53372481]
  [1.32137078 1.00594733 1.33486346 1.20980453 1.20907052]]

 [[1.59928867 1.27620136 1.05585533 1.51427482 1.80348773]
  [1.6332484  1.92814138 1.21252654 1.79758725 1.58489046]
  [1.62901411 1.55465762 1.91307846 1.08720965 1.64480321]]]


In [33]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
#Values in d are values in a adding 1

[[[0.16445687 0.84667536 0.30726898 0.80098137 0.19631435]
  [0.02365554 0.30499958 0.53091093 0.49148912 0.53372481]
  [0.32137078 0.00594733 0.33486346 0.20980453 0.20907052]]

 [[0.59928867 0.27620136 0.05585533 0.51427482 0.80348773]
  [0.6332484  0.92814138 0.21252654 0.79758725 0.58489046]
  [0.62901411 0.55465762 0.91307846 0.08720965 0.64480321]]]
[[[1.16445687 1.84667536 1.30726898 1.80098137 1.19631435]
  [1.02365554 1.30499958 1.53091093 1.49148912 1.53372481]
  [1.32137078 1.00594733 1.33486346 1.20980453 1.20907052]]

 [[1.59928867 1.27620136 1.05585533 1.51427482 1.80348773]
  [1.6332484  1.92814138 1.21252654 1.79758725 1.58489046]
  [1.62901411 1.55465762 1.91307846 1.08720965 1.64480321]]]


In [36]:
#12. Multiply a and c. Assign the result to e.
e = a*c
print(e)

[[[0.16445687 0.84667536 0.30726898 0.80098137 0.19631435]
  [0.02365554 0.30499958 0.53091093 0.49148912 0.53372481]
  [0.32137078 0.00594733 0.33486346 0.20980453 0.20907052]]

 [[0.59928867 0.27620136 0.05585533 0.51427482 0.80348773]
  [0.6332484  0.92814138 0.21252654 0.79758725 0.58489046]
  [0.62901411 0.55465762 0.91307846 0.08720965 0.64480321]]]


In [42]:
#13. Does e equal to a? Why or why not?
if e.all() == a.all() :
    print ('true')
else :
    print ('false')   
#Yes, they're equal because e is a multiplied by 1 

true


In [75]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
print(d_max)
d_mean = np.mean(d)
print(d_mean)
d_min = np.min(d)
print(d_min)

1.9281413821702609
1.450526616914729
1.0059473265583585


In [45]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty((2, 3, 5))
print(f)

[[[0.16445687 0.84667536 0.30726898 0.80098137 0.19631435]
  [0.02365554 0.30499958 0.53091093 0.49148912 0.53372481]
  [0.32137078 0.00594733 0.33486346 0.20980453 0.20907052]]

 [[0.59928867 0.27620136 0.05585533 0.51427482 0.80348773]
  [0.6332484  0.92814138 0.21252654 0.79758725 0.58489046]
  [0.62901411 0.55465762 0.91307846 0.08720965 0.64480321]]]


In [ ]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
"""If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question."""


In [163]:
#each value in d in f:
#d_min < x < d_mean = 25
#d_mean < x < d_max = 75
#x = d_mean = 50 
#d_min = 0 
#d_max = 100
for x in d:
    for i in x:
        for j in i:
            if d_min < j < d_mean:
                j==25
            if d_mean < j < d_max:
                j==75
            if j == d_mean:
                j==50
            if j == d_min:
                j==0
            if j == d_max:
                j==100
f(j)
f = np.array(f)
print (f)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
#17. Print d and f. Do you have your expected f?
"""For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])"""
        

In [ ]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""